### PR TITLE
Update uploader_daemon.py

### PR DESCRIPTION
**Pull request by thunder2k**
This should solve the issue with accented characters.
unidecode must also be inserted in the prerequisites and must be pip3 installed for this patch to work

### CODE REVIEW

**Review by jaymoulin — APPROVED** [review]

**Comment by jaymoulin** [comment]
I'd rather not depend on another dependency to achieve this. I'm pretty sure we can just decode to utf-8

**Comment by thunder2k** [comment]
I wasn't able to achieve that but I'm pretty new to python. I'm running it with this changes on my local machine and it's working flawlessly

**Comment by jaymoulin** [comment]
I'm not saying your code doesn't work.

I'm saying that it requires an external dependency that need a major update to the product. I'm pretty sure we could fix this without needing to require an external dependency by achieving this with native conversions

**Review by jaymoulin — CHANGES_REQUESTED** [review]
unicode can be encoded to utf8 with `u'string'.encode('utf-8')`

**Comment by thunder2k** [comment]
I'm not able to test this as I'm away.. I'll try it tomowow and let you know

**Comment by jaymoulin** [comment]
No problem ;)

**Comment by thunder2k** [comment]
So I just tested this but I got the same errors. I've added a print statement to check how was it encoded.
this is how I implemented the fix:
`result = requests.request('GET', self.uri + "/", data={"path": file_path.encode('utf-8')})`
and this is the result:
```
INFO:__main__:Detected new files!
INFO:__main__:Uploading /home/pi/Music/Emma Marrone - La Mia Città.mp3?
Running DeduplicateApi EXISTS function on b'/home/pi/Music/Emma Marrone - La Mia Citt\xc3\xa0.mp3'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/pi/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/pi/.local/lib/python3.5/site-packages/watchdog/observers/api.py", line 199, in run
    self.dispatch_events(self.event_queue, self.timeout)
  File "/home/pi/.local/lib/python3.5/site-packages/watchdog/observers/api.py", line 368, in dispatch_events
    handler.dispatch(event)
  File "/home/pi/.local/lib/python3.5/site-packages/watchdog/events.py", line 330, in dispatch
    _method_map[event_type](event)
  File "/home/pi/google-music-manager-uploader/google_music_manager_uploader/uploader_daemon.py", line 58, in on_created
    deduplicate_api=self.deduplicate_api,
  File "/home/pi/google-music-manager-uploader/google_music_manager_uploader/uploader_daemon.py", line 93, in upload_file
    exists = deduplicate_api.exists(file_path)
  File "/home/pi/google-music-manager-uploader/google_music_manager_uploader/uploader_daemon.py", line 31, in exists
    result = requests.request('GET', self.uri + "/", data={"path": file_path.encode('utf-8')})
  File "/home/pi/.local/lib/python3.5/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```
Do you have any other suggestions?

**Comment by jaymoulin** [comment]
I fixed the API, you can pull the latest (1.0.1) image, this should fix your issue (#3, #4 )

**Comment by thunder2k** [comment]
> I fixed the API, you can pull the latest (1.0.1) image, this should fix your issue (#3, #4 )

How can I update the docker image? I've run the command from the readme but it doesn't seem to have it updated or, if it did, the fix doesn't work

**Comment by jaymoulin** [comment]
> > I fixed the API, you can pull the latest (1.0.1) image, this should fix your issue (#3, #4 )
> 
> How can I update the docker image? I've run the command from the readme but it doesn't seem to have it updated or, if it did, the fix doesn't work

With docker-compose:

```
docker-compose pull && docker-compose up -d
```

With docker, something like depending on your setup:
```
docker pull jaymoulin/google-musicmanager-dedup-api
docker rm -f  googlemusic-dedup
docker run -d --restart=always -p 80:80 -v /path/to/your/db:/app/db --name googlemusic-dedup jaymoulin/google-musicmanager-dedup-api
```
```

**Comment by thunder2k** [comment]
Cool,
It's working now, thanks!
Now I only need to understand the - d parameter bit (I've sent you an email about it)

**Comment by jaymoulin** [comment]
`-d` is the parameter for `directory`. It's used like this :
 - no parameter : scan current directory
 - `-d XXX`: scan the XXX directory
 - `- d`: 2 parametres : `-` and `d` both not interpreted so fallback to no parameter : scan current directory

**Comment by thunder2k** [comment]
That's what I was thinking.. but from your email:
`Just be careful you passed '-d' parameter instead of '- d' which doesn't mean the same thing and will scan only the current directory
`
I think you meant the opposite :)

**Pull request closed without merging**
